version: '3.8'

networks:
  wml_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:
  whats_my_line:
    container_name: whats_my_line
    image: tomi12345/whatsmyline_v2:dev
    restart: unless-stopped
    env_file:
      - /home/environment/wml-prod.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    expose:
      - "5000"
    ports:
      - "5001:5000"  # Added port mapping
    stdin_open: true
    tty: true
    volumes:
      - ./logs:/logs
    networks:
      wml_network:
        ipv4_address: 192.168.1.100

volumes:
  logs:

