version: '3.8'

services:
  app:
    restart: always
    build:
      context: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
