version: '3.8'

services:
  backend:
    build: ./server
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./server/:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=whats_my_line_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
