version: '3.8'

services:
  backend:
    platform: linux/x86_64
    build: ./server
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./server/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
    environment:
      - TZ=Europe/Helsinki  # Set timezone for frontend

  frontend:
    platform: linux/x86_64
    image: frontend
    build: ./client_vite
    environment:
      - TZ=Europe/Helsinki  # Set timezone for frontend
    volumes:
     - "./client_vite/src:/usr/src/app/src"
    depends_on:
      - backend

  db:
    platform: linux/x86_64
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=whats_my_line_db
      - TZ=Europe/Helsinki  # Already set, kept for consistency
      - PGTZ=Europe/Helsinki  # Set PostgreSQL session timezone
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  nginx:
    platform: linux/x86_64
    image: nginx:1.20.1
    environment:
      - TZ=Europe/Helsinki
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend

volumes:
  node_modules:
  postgres_data:
