version: '3.8'

services:
  backend:
    platform: linux/x86_64
    build: ./server
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./server/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db

  # frontend:
  #   build: ./client
  #   container_name: react-frontend
  #   volumes:
  #     - ./client/src:/usr/src/app/src
  #     - ./client/public/index.html:/usr/src/app/public/index.html
  #   ports:
  #     - 5002:5000
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     - backend

  frontend:
    platform: linux/x86_64
    image: frontend
    build: ./client_vite
    volumes:
     - "./client_vite/src:/usr/src/app/src"
    # - "./client_vite/node_modules:/usr/src/app/node_modules"
   #  - "./client_vite/vite.config.ts:/usr/src/app/vite.config.ts"
    # volumes:
    #   - ./client_vite:/usr/src/app
    
    #   - ./client_vite:/usr/src/app # Let us modify the contents of the container locally
    # # volumes:
    #   - node_modules:/usr/src/app/node_modules
    #   - ./client_vite:/usr/src/app
    depends_on:
      - backend

  db:
    platform: linux/x86_64
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=whats_my_line_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  # adminer:
  #   image: adminer:4
  #   restart: always
  #   environment:
  #     - ADMINER_DESIGN=db
  #   ports:
  #     - 8083:8080

  nginx:
    platform: linux/x86_64
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend

volumes:
  node_modules:
  postgres_data:
