"""empty message

Revision ID: 2001ba741dfa
Revises: 6233c57852b5
Create Date: 2025-08-15 19:26:34.396082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2001ba741dfa'
down_revision = '6233c57852b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('script_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.drop_column('opened_on')
        batch_op.drop_column('created_on')
        batch_op.drop_column('modified_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('opened_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('script_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('updated')
        batch_op.drop_column('created')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
