"""empty message

Revision ID: 4c4de00db559
Revises: 53cc2d41bbc4
Create Date: 2025-02-10 19:34:26.198508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4de00db559'
down_revision = '53cc2d41bbc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opened_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.drop_column('opened_on')

    # ### end Alembic commands ###
