"""empty message

Revision ID: 6233c57852b5
Revises: 414b989f94db
Create Date: 2025-08-13 16:56:29.794652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6233c57852b5'
down_revision = '414b989f94db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.String()))
        batch_op.drop_constraint(batch_op.f('users_user_id_key'), type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(), autoincrement=False))
        batch_op.create_unique_constraint(batch_op.f('users_user_id_key'), ['user_id'])
        batch_op.drop_column('provider_id')

    # ### end Alembic commands ###
