"""empty message

Revision ID: 9ee2c5db3fcd
Revises: c4718ff20ceb
Create Date: 2025-08-13 16:48:09.581281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ee2c5db3fcd'
down_revision = 'c4718ff20ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('registered_on',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('users_picture_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('users_picture_key'), ['picture'])
        batch_op.alter_column('registered_on',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###
