"""empty message

Revision ID: f7db2beecf1b
Revises: fea451ebcbff
Create Date: 2024-05-06 14:03:15.756761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7db2beecf1b'
down_revision = 'fea451ebcbff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   with op.batch_alter_table('scripts', schema=None) as batch_op:
        # Specify a USING clause for the type conversion
        batch_op.alter_column(
            'user_id',
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            nullable=True,
            postgresql_using="user_id::integer"
        )
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
