"""add_deleted_at_column_to_scripts

Revision ID: fea451ebcbff
Revises: 50f898ec3e9c
Create Date: 2024-05-04 11:50:07.000991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fea451ebcbff'
down_revision = '50f898ec3e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.alter_column('modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
