name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build React client
      run: |
        cd client
        npm install
        npm run build

    - name: Copy React build to Flask server folder
      run: |
        mkdir server/static
        cp -r client/build/* server/
        
    - name: Install Python dependencies
      run: |
        cd server
        pip install -r requirements.txt
    
    - name: Set Heroku config variables
      env:
        HEROKU_APP_NAME: dramatify
      run: |
        heroku config:set PROJECT_PATH=server -a $HEROKU_APP_NAME

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: dramatify
      run: |
        cd server
        git init
        git add .
        git commit -m "Deploy to Heroku"
        heroku git:remote -a $HEROKU_APP_NAME
        git push heroku main --force
