name: Docker Image CI

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: file permission
        run: chmod +x server/entrypoint.sh

      - name: Load environment variables
        run: source .env.dev

      - name: Build amd run frontend tests
        run: docker-compose -f docker-compose.yml up -d

      - name: Run backend Tests
        run: |
          docker-compose -f docker-compose.yml exec -T backend python manage.py run_tests | tee tests_output.txt # Run tests

          if grep -q "FAILED tests" tests_output.txt; then
            echo "Pattern 'FAILED tests' found in test results. Exiting with code 1."
            exit 1
          else
            echo "Pattern 'FAILED tests' not found in test results."
          fi
