name: Docker Image CI

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: file permission
        run: chmod +x server/entrypoint.sh

      - name: Load environment variables
        run: source .env.dev

      - name: Build
        run: docker-compose -f docker-compose.yml up -d

      - name: Delay for 3 seconds before running tests
        run: sleep 3

      - name: Run frontend tests
        run: |
          docker exec react-frontend npm run test | tee frontend_tests_output.txt

          if grep -q "failed" frontend_tests_output.txt; then
            echo "Pattern 'failed' found in frontend test results. Exiting with code 1."
            exit 1
          else
            echo "Pattern 'failed' not found in frontend test results."
          fi
